/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavisha Lashani
 */
public class BookDetailsChange1 extends javax.swing.JFrame {

    /**
     * Creates new form BookDetailsChange1
     */
    private int bookID;
    public BookDetailsChange1(int bookID) {
        initComponents();
        this.bookID = bookID;

        try {
        DBConnector dbConnector = new DBConnector();
        Books book = dbConnector.getBookDetails(bookID);
        
        if (book != null) {
            String BookID = String.valueOf(book.getBookID());
            TextField_BoookIDChange.setText(BookID);
            TextField_BoookNameChange.setText(book.getBookName());
            TextField_AuotherChange.setText(book.getAuthor());
            TextField_DateChange.setText(book.getDate());
            String quantity = String.valueOf(book.getQuantity());
            TextField_QuantityChange.setText(quantity);
            
        } else {
            JOptionPane.showMessageDialog(null, "No student found with the provided ID.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error fetching student details: " + e.getMessage());
    }

    }
    
    public BookDetailsChange1(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Aouther = new javax.swing.JPanel();
        Label_BookID2 = new javax.swing.JLabel();
        Label_studentNameIcon6 = new javax.swing.JLabel();
        Label_BookName1 = new javax.swing.JLabel();
        Label_AddressIcon6 = new javax.swing.JLabel();
        TextField_BoookNameChange = new javax.swing.JTextField();
        Label_BookNameError1 = new javax.swing.JLabel();
        Label_Auother1 = new javax.swing.JLabel();
        Label_AddressIcon7 = new javax.swing.JLabel();
        TextField_AuotherChange = new javax.swing.JTextField();
        Label_AuotherError1 = new javax.swing.JLabel();
        Label_BookAddDate1 = new javax.swing.JLabel();
        Label_ContactNoIcon3 = new javax.swing.JLabel();
        TextField_DateChange = new javax.swing.JTextField();
        Label_DateError1 = new javax.swing.JLabel();
        Label_quantity1 = new javax.swing.JLabel();
        Label_QuantityIcon1 = new javax.swing.JLabel();
        TextField_QuantityChange = new javax.swing.JTextField();
        Label_quantityError1 = new javax.swing.JLabel();
        Label_ChangeDetails1 = new javax.swing.JLabel();
        Button_BookDetailsChange = new javax.swing.JButton();
        TextField_BoookIDChange = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Button_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Aouther.setBackground(new java.awt.Color(5, 11, 175));

        Label_BookID2.setText("Book ID");

        Label_studentNameIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/id.png"))); // NOI18N

        Label_BookName1.setText("Book Name");

        Label_AddressIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/open-book (1).png"))); // NOI18N

        Label_BookNameError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_BookNameError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_BookNameError1.setText("BooK Name");

        Label_Auother1.setText("Auother");

        Label_AddressIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/writing.png"))); // NOI18N

        Label_AuotherError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_AuotherError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_AuotherError1.setText("Auother");

        Label_BookAddDate1.setText("Date");

        Label_ContactNoIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar.png"))); // NOI18N

        Label_DateError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_DateError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_DateError1.setText("Contact Number");

        Label_quantity1.setText("Quantity");

        Label_QuantityIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/coins.png"))); // NOI18N

        Label_quantityError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_quantityError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_quantityError1.setText("Quantity");

        Label_ChangeDetails1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_ChangeDetails1.setText("Book Details Change");

        Button_BookDetailsChange.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_BookDetailsChange.setText("Change");
        Button_BookDetailsChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BookDetailsChangeActionPerformed(evt);
            }
        });

        TextField_BoookIDChange.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Button_exit.setBackground(new java.awt.Color(153, 0, 0));
        Button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close (1).png"))); // NOI18N
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_AoutherLayout = new javax.swing.GroupLayout(jPanel_Aouther);
        jPanel_Aouther.setLayout(jPanel_AoutherLayout);
        jPanel_AoutherLayout.setHorizontalGroup(
            jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(Button_BookDetailsChange, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Label_ChangeDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Label_BookID2)
                        .addGap(279, 279, 279))
                    .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                        .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_AddressIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_ContactNoIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_QuantityIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_AddressIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_studentNameIcon6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_QuantityChange)
                            .addComponent(TextField_DateChange)
                            .addComponent(TextField_AuotherChange)
                            .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Auother1)
                                    .addComponent(Label_quantityError1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_DateError1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_AuotherError1)
                                    .addComponent(Label_BookAddDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_BookNameError1)
                                    .addComponent(TextField_BoookNameChange, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_BookName1)
                                    .addComponent(TextField_BoookIDChange, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_AoutherLayout.setVerticalGroup(
            jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AoutherLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Label_ChangeDetails1)
                .addGap(18, 18, 18)
                .addComponent(Label_BookID2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_studentNameIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_BoookIDChange, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AoutherLayout.createSequentialGroup()
                        .addComponent(Label_BookName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_BoookNameChange, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_AddressIcon6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_BookNameError1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_Auother1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_AuotherChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_AddressIcon7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_AuotherError1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_BookAddDate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_DateChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_ContactNoIcon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_DateError1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_quantity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AoutherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_QuantityChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_QuantityIcon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_quantityError1)
                .addGap(18, 18, 18)
                .addComponent(Button_BookDetailsChange, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Aouther, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Aouther, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void bookDeatails(String returnstring) {

        String[] bookDeatails = returnstring.split("\\|");

        String splitBookId = bookDeatails[0];
        String splitName = bookDeatails[1];
        String splitAuthor = bookDeatails[2];
        String splitDate = bookDeatails[3];
        String splitQuantity = bookDeatails[4];

        TextField_BoookIDChange.setText(splitBookId);
        TextField_BoookNameChange.setText(splitName);
        TextField_AuotherChange.setText(splitAuthor);
        TextField_DateChange.setText(splitDate);
        TextField_QuantityChange.setText(splitQuantity);

        TextField_BoookIDChange.setEditable(false);
    }


    private void Button_BookDetailsChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BookDetailsChangeActionPerformed
        String bookname = TextField_BoookNameChange.getText();
        String auother = TextField_AuotherChange.getText();
        String date = TextField_DateChange.getText();
        String qua = TextField_QuantityChange.getText();
        int quantity = Integer.parseInt(TextField_QuantityChange.getText());
        String bookid = TextField_BoookIDChange.getText();
        int intbookid = Integer.parseInt(TextField_BoookIDChange.getText());

        boolean textfeildEmty = false;

        if (bookname.equals("")) {
            Label_BookNameError1.setVisible(true);
            Label_BookNameError1.setText("Please enter book name");
            textfeildEmty = true;
        }
        if (auother.equals("")) {
            Label_AuotherError1.setVisible(true);
            Label_AuotherError1.setText("Please Eneter Auother name");
            textfeildEmty = true;
        }
        if (date.equals("")) {
            Label_DateError1.setVisible(true);
            Label_DateError1.setText("Please Enter Date");
            textfeildEmty = true;
        }
        if (qua.equals("")) {
            Label_quantityError1.setVisible(true);
            Label_quantityError1.setText("Please Entere the Quantity");
            textfeildEmty = true;
        }

        if (!textfeildEmty) {
            try {
                DBConnector dbc = new DBConnector();
                int rs = dbc.EditBookDetails(intbookid, bookname, auother, date, quantity);

                if (rs > 0) {
                    JOptionPane.showMessageDialog(null, "Change Succesfull.", "Success", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(null, "PLease try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Button_BookDetailsChangeActionPerformed

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
       dispose();
    }//GEN-LAST:event_Button_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetailsChange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetailsChange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetailsChange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetailsChange1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookDetailsChange1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_BookDetailsChange;
    private javax.swing.JButton Button_exit;
    private javax.swing.JLabel Label_AddressIcon6;
    private javax.swing.JLabel Label_AddressIcon7;
    private javax.swing.JLabel Label_Auother1;
    private javax.swing.JLabel Label_AuotherError1;
    private javax.swing.JLabel Label_BookAddDate1;
    private javax.swing.JLabel Label_BookID2;
    private javax.swing.JLabel Label_BookName1;
    private javax.swing.JLabel Label_BookNameError1;
    private javax.swing.JLabel Label_ChangeDetails1;
    private javax.swing.JLabel Label_ContactNoIcon3;
    private javax.swing.JLabel Label_DateError1;
    private javax.swing.JLabel Label_QuantityIcon1;
    private javax.swing.JLabel Label_quantity1;
    private javax.swing.JLabel Label_quantityError1;
    private javax.swing.JLabel Label_studentNameIcon6;
    private javax.swing.JTextField TextField_AuotherChange;
    private javax.swing.JTextField TextField_BoookIDChange;
    private javax.swing.JTextField TextField_BoookNameChange;
    private javax.swing.JTextField TextField_DateChange;
    private javax.swing.JTextField TextField_QuantityChange;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Aouther;
    // End of variables declaration//GEN-END:variables
}
