/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Kavisha Lashani
 */
public class BookIssue extends javax.swing.JFrame {

    /**
     * Creates new form BookIssue
     */
    private Timer timer;

    
    public BookIssue() {
        initComponents();
        Label_TopicBookIssueError.setVisible(false);
        Label_StudentIDError.setVisible(false);

        BookIssueTable();
    }

    public void BookIssueTable() {
        try {
            DBConnector dbc = new DBConnector();

            Object[][] data = dbc.BookIssueTable();
            int rows = data.length;

            DefaultTableModel tableModel = (DefaultTableModel) Table_bookIssue.getModel();
            for (Object[] row : data) {
                tableModel.addRow(row);
            }
            DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
            leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);

            for (int i = 0; i < Table_bookIssue.getColumnCount(); i++) {
                Table_bookIssue.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
            }
            Table_bookIssue.setDefaultEditor(Object.class, null);

        } catch (SQLException ex) {
            Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_BookIssue = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Label_TopicBookIssue = new javax.swing.JLabel();
        TextField_BookID = new javax.swing.JTextField();
        Label_TopicBookIssue1 = new javax.swing.JLabel();
        Label_TopicBookIssueError = new javax.swing.JLabel();
        Label_TopicBookIssue3 = new javax.swing.JLabel();
        Label_Date = new javax.swing.JLabel();
        TextField_ReturnDate = new javax.swing.JTextField();
        Label_StudentIDError = new javax.swing.JLabel();
        TextField_StudentID1 = new javax.swing.JTextField();
        Label_ReturnDate = new javax.swing.JLabel();
        Label_StudentID3 = new javax.swing.JLabel();
        Label_StudentID1 = new javax.swing.JLabel();
        Button_BookIssued = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_bookIssue = new javax.swing.JTable();
        Label_TopicBookIssue2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Button_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_BookIssue.setBackground(new java.awt.Color(117, 16, 204));

        jPanel2.setBackground(new java.awt.Color(5, 11, 175));

        Label_TopicBookIssue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_TopicBookIssue.setText("Book Issue");

        TextField_BookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_BookIDKeyPressed(evt);
            }
        });

        Label_TopicBookIssue1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_TopicBookIssue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/open-book (1).png"))); // NOI18N

        Label_TopicBookIssueError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_TopicBookIssueError.setForeground(new java.awt.Color(204, 0, 0));
        Label_TopicBookIssueError.setText("Book ID");

        Label_TopicBookIssue3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_TopicBookIssue3.setText("Book ID");

        Label_Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_Date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar.png"))); // NOI18N

        Label_StudentIDError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_StudentIDError.setForeground(new java.awt.Color(204, 0, 0));
        Label_StudentIDError.setText("Student ID");

        TextField_StudentID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_StudentID1KeyPressed(evt);
            }
        });

        Label_ReturnDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_ReturnDate.setText("Return Date");

        Label_StudentID3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_StudentID3.setText("Student ID");

        Label_StudentID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Label_StudentID1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user (1).png"))); // NOI18N

        Button_BookIssued.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_BookIssued.setText("Issue");
        Button_BookIssued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BookIssuedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_StudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_TopicBookIssue1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_TopicBookIssue3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_TopicBookIssueError, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_StudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_StudentID3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_StudentIDError, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Button_BookIssued, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Label_TopicBookIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Label_TopicBookIssue)
                .addGap(40, 40, 40)
                .addComponent(Label_TopicBookIssue3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_TopicBookIssue1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Label_TopicBookIssueError)
                .addGap(34, 34, 34)
                .addComponent(Label_StudentID3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_StudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_StudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Label_StudentIDError)
                .addGap(28, 28, 28)
                .addComponent(Label_ReturnDate)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_BookIssued, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        Table_bookIssue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Issued Date", "Received Date", "Student ID"
            }
        ));
        jScrollPane5.setViewportView(Table_bookIssue);

        Label_TopicBookIssue2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_TopicBookIssue2.setText("Issued Book Details");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Button_exit.setBackground(new java.awt.Color(153, 0, 0));
        Button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close (1).png"))); // NOI18N
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_BookIssueLayout = new javax.swing.GroupLayout(Panel_BookIssue);
        Panel_BookIssue.setLayout(Panel_BookIssueLayout);
        Panel_BookIssueLayout.setHorizontalGroup(
            Panel_BookIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BookIssueLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_BookIssueLayout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(Label_TopicBookIssue2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BookIssueLayout.setVerticalGroup(
            Panel_BookIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BookIssueLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_TopicBookIssue2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(Panel_BookIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel_BookIssue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel_BookIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BookIssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BookIssuedActionPerformed
        String bookidtxt = TextField_BookID.getText();
    String studentidtxt = TextField_StudentID1.getText();
    String ReturnDate = TextField_ReturnDate.getText();
    boolean textFeildEmpty = false;

    // Validate inputs
    if (bookidtxt.equals("")) {
        Label_TopicBookIssueError.setVisible(true);
        Label_TopicBookIssueError.setText("Please Enter the Book ID");
        textFeildEmpty = true;
    }
    if (studentidtxt.equals("")) {
        Label_StudentIDError.setVisible(true);
        Label_StudentIDError.setText("Please Enter the Student ID");
        textFeildEmpty = true;
    }

    if (!textFeildEmpty) {
        int bookid = Integer.parseInt(bookidtxt);
        int studentid = Integer.parseInt(studentidtxt);

        try {
            DBConnector dbc = new DBConnector();
            int status = dbc.IssueBook(bookid, studentid, ReturnDate);
            if (status > 0) {
                JOptionPane.showMessageDialog(null, "Book Issued Successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Issue Failed. Please Try Again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_Button_BookIssuedActionPerformed

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        DashBoard db = new DashBoard();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_exitActionPerformed

    private void TextField_BookIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BookIDKeyPressed
        Label_TopicBookIssueError.setVisible(false);
    }//GEN-LAST:event_TextField_BookIDKeyPressed

    private void TextField_StudentID1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_StudentID1KeyPressed
        Label_StudentIDError.setVisible(false);
    }//GEN-LAST:event_TextField_StudentID1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookIssue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_BookIssued;
    private javax.swing.JButton Button_exit;
    private javax.swing.JLabel Label_Date;
    private javax.swing.JLabel Label_ReturnDate;
    private javax.swing.JLabel Label_StudentID1;
    private javax.swing.JLabel Label_StudentID3;
    private javax.swing.JLabel Label_StudentIDError;
    private javax.swing.JLabel Label_TopicBookIssue;
    private javax.swing.JLabel Label_TopicBookIssue1;
    private javax.swing.JLabel Label_TopicBookIssue2;
    private javax.swing.JLabel Label_TopicBookIssue3;
    private javax.swing.JLabel Label_TopicBookIssueError;
    private javax.swing.JPanel Panel_BookIssue;
    private javax.swing.JTable Table_bookIssue;
    private javax.swing.JTextField TextField_BookID;
    private javax.swing.JTextField TextField_ReturnDate;
    private javax.swing.JTextField TextField_StudentID1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
