/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Kavisha Lashani
 */
public class BookManagement extends javax.swing.JFrame {

    /**
     * Creates new form BookManagement
     */
    public BookManagement() {
        initComponents();
        Label_AddBookIDError.setVisible(false);
        Label_BookNameError.setVisible(false);
        Label_AuotherError.setVisible(false);
        Label_DateError.setVisible(false);
        Label_quantityError.setVisible(false);
        Label_RomoveBookIDError1.setVisible(false);
        Label_AddBookIDErrorChange1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Label_AddBook = new javax.swing.JLabel();
        Label_BookID = new javax.swing.JLabel();
        Label_AddBookIDError = new javax.swing.JLabel();
        Label_BookName = new javax.swing.JLabel();
        TextField_Auother = new javax.swing.JTextField();
        Label_BookNameError = new javax.swing.JLabel();
        Label_Auother = new javax.swing.JLabel();
        Label_AuotherError = new javax.swing.JLabel();
        Label_BookAddDate = new javax.swing.JLabel();
        Label_AddressIcon4 = new javax.swing.JLabel();
        TextField_AddBookID = new javax.swing.JTextField();
        Label_studentNameIcon3 = new javax.swing.JLabel();
        TextField_BoookName = new javax.swing.JTextField();
        Label_AddressIcon5 = new javax.swing.JLabel();
        TextField_quantity = new javax.swing.JTextField();
        Label_ContactNoIcon2 = new javax.swing.JLabel();
        Label_DateError = new javax.swing.JLabel();
        TextField_Date1 = new javax.swing.JTextField();
        Label_quantity = new javax.swing.JLabel();
        Label_quantityError = new javax.swing.JLabel();
        Label_QuantityIcon = new javax.swing.JLabel();
        Button_addbook = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        Label_RemoveBook = new javax.swing.JLabel();
        Label_BookID1 = new javax.swing.JLabel();
        Label_RomoveBookIDError1 = new javax.swing.JLabel();
        Button_Remove = new javax.swing.JButton();
        TextField_RemoveBook = new javax.swing.JTextField();
        Label_studentNameIcon4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Label_ChangeDetails2 = new javax.swing.JLabel();
        TextField_AddBookID3 = new javax.swing.JTextField();
        Label_BookIDChange1 = new javax.swing.JLabel();
        Label_AddBookIDErrorChange1 = new javax.swing.JLabel();
        Label_studentNameIcon7 = new javax.swing.JLabel();
        Button_SearchChange1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Button_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel7.setBackground(new java.awt.Color(117, 16, 204));

        jPanel8.setBackground(new java.awt.Color(5, 11, 175));
        jPanel8.setPreferredSize(new java.awt.Dimension(420, 578));

        Label_AddBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_AddBook.setText("Add Book");

        Label_BookID.setText("Book ID");

        Label_AddBookIDError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_AddBookIDError.setForeground(new java.awt.Color(204, 0, 0));
        Label_AddBookIDError.setText("Student Name");

        Label_BookName.setText("Book Name");

        Label_BookNameError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_BookNameError.setForeground(new java.awt.Color(204, 0, 0));
        Label_BookNameError.setText("BooK Name");

        Label_Auother.setText("Auother");

        Label_AuotherError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_AuotherError.setForeground(new java.awt.Color(204, 0, 0));
        Label_AuotherError.setText("Auother");

        Label_BookAddDate.setText("Date");

        Label_AddressIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/writing.png"))); // NOI18N

        Label_studentNameIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/id.png"))); // NOI18N

        Label_AddressIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/open-book (1).png"))); // NOI18N

        Label_ContactNoIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar.png"))); // NOI18N

        Label_DateError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_DateError.setForeground(new java.awt.Color(204, 0, 0));
        Label_DateError.setText("Contact Number");

        Label_quantity.setText("Quantity");

        Label_quantityError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_quantityError.setForeground(new java.awt.Color(204, 0, 0));
        Label_quantityError.setText("Quantity");

        Label_QuantityIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/coins.png"))); // NOI18N

        Button_addbook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_addbook.setText("ADD");
        Button_addbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_addbookMouseClicked(evt);
            }
        });
        Button_addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_addbookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_AddressIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_ContactNoIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_AddressIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_QuantityIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_quantityError, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(Label_DateError, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_AuotherError)
                            .addComponent(Label_Auother)
                            .addComponent(Label_BookID)
                            .addComponent(Label_BookAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_BookNameError)
                            .addComponent(Label_BookName)
                            .addComponent(TextField_Date1)
                            .addComponent(TextField_BoookName)
                            .addComponent(TextField_Auother)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Label_studentNameIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(Label_AddBookIDError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TextField_AddBookID))))
                .addGap(421, 421, 421))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Label_AddBook))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Button_addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_AddBook)
                .addGap(18, 18, 18)
                .addComponent(Label_BookID)
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_studentNameIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_AddBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_AddBookIDError)
                .addGap(22, 22, 22)
                .addComponent(Label_BookName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_BoookName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_AddressIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_BookNameError)
                .addGap(18, 18, 18)
                .addComponent(Label_Auother)
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Label_AddressIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_AuotherError)
                        .addGap(18, 18, 18)
                        .addComponent(Label_BookAddDate))
                    .addComponent(TextField_Auother, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_ContactNoIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_DateError)
                .addGap(24, 24, 24)
                .addComponent(Label_quantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_QuantityIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_quantityError)
                .addGap(46, 46, 46)
                .addComponent(Button_addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(5, 11, 175));
        jPanel9.setPreferredSize(new java.awt.Dimension(420, 578));

        Label_RemoveBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_RemoveBook.setText("Remove Book");

        Label_BookID1.setText("Book ID");

        Label_RomoveBookIDError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_RomoveBookIDError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_RomoveBookIDError1.setText("Student Name");

        Button_Remove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_Remove.setText("Remove");
        Button_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemoveActionPerformed(evt);
            }
        });

        Label_studentNameIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/id.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(Label_studentNameIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Label_RomoveBookIDError1))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_RemoveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label_BookID1)
                        .addGap(657, 657, 657))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Label_RemoveBook))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Button_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_RemoveBook)
                .addGap(83, 83, 83)
                .addComponent(Label_BookID1)
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_studentNameIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_RemoveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_RomoveBookIDError1)
                .addGap(52, 52, 52)
                .addComponent(Button_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(5, 11, 175));

        Label_ChangeDetails2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_ChangeDetails2.setText("Book Details Change");

        Label_BookIDChange1.setText("Book ID");

        Label_AddBookIDErrorChange1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_AddBookIDErrorChange1.setForeground(new java.awt.Color(204, 0, 0));
        Label_AddBookIDErrorChange1.setText("Student Name");

        Label_studentNameIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/id.png"))); // NOI18N

        Button_SearchChange1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_SearchChange1.setText("Search");
        Button_SearchChange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchChange1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Label_studentNameIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_BookIDChange1)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addComponent(Label_ChangeDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addComponent(TextField_AddBookID3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addComponent(Label_AddBookIDErrorChange1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_SearchChange1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Label_ChangeDetails2)
                .addGap(46, 46, 46)
                .addComponent(Label_BookIDChange1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_AddBookID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_studentNameIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_AddBookIDErrorChange1)
                .addGap(36, 36, 36)
                .addComponent(Button_SearchChange1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Button_exit.setBackground(new java.awt.Color(153, 0, 0));
        Button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close (1).png"))); // NOI18N
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_addbookActionPerformed

        boolean textFeilEmty = false;
        int bookid = Integer.parseInt(TextField_AddBookID.getText());
        String bookidtxt = TextField_AddBookID.getText();
        String bookName = TextField_BoookName.getText();
        String auother = TextField_Auother.getText();
        String date = TextField_Date1.getText();
        int quantity = Integer.parseInt(TextField_quantity.getText());
        String quantityText = TextField_quantity.getText();

        if (bookidtxt.equals("")) {
            Label_AddBookIDError.setVisible(true);
            Label_AddBookIDError.setText("Please Enetr the Book Id");
            textFeilEmty = false;
        }
        if (bookName.equals("")) {
            Label_BookNameError.setVisible(true);
            Label_BookNameError.setText("Please Enter The Book Name");
            textFeilEmty = false;
        }
        if (auother.equals("")) {
            Label_AuotherError.setVisible(true);
            Label_AuotherError.setText("Please Eneter The Auother Name");
            textFeilEmty = false;
        }
        if (date.equals("")) {
            Label_DateError.setVisible(true);
            Label_DateError.setText("Please Entere The Emill");
            textFeilEmty = false;
        }
        if (quantityText.equals("")) {
            Label_quantityError.setVisible(true);
            Label_quantityError.setText("Please  Enter The Quantity");
            textFeilEmty = false;
        }

        if (!textFeilEmty) {
            try {
                DBConnector dbc = new DBConnector();
                int status = dbc.AddBook(bookid, bookName, auother, date, quantity);
                if (status > 0) {
                    JOptionPane.showMessageDialog(null, "Book Add Success.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "PLease Try Again.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_Button_addbookActionPerformed

    private void Button_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemoveActionPerformed
        String removebook = TextField_RemoveBook.getText();
        
        if (removebook.equals("")) {
            Label_RomoveBookIDError1.setVisible(true);
            Label_RomoveBookIDError1.setText(String.valueOf("Please Eneter the Book Id"));
            
        } else {

            try {
                int intremovebook = Integer.parseInt(removebook);
                DBConnector dbc = new DBConnector();
                int status = dbc.RemoveBook(intremovebook);
                if (status > 0) {
                    JOptionPane.showMessageDialog(null, "Book Remove Success.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "PLease Try Again.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_Button_RemoveActionPerformed

    private void Button_SearchChange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchChange1ActionPerformed
        int bookid = Integer.parseInt(TextField_AddBookID3.getText());


    try {
        DBConnector dbConnector = new DBConnector();
        boolean exists = dbConnector.CheckBookID(bookid);
        
        if (exists) {
            BookDetailsChange1 change = new BookDetailsChange1(bookid);
            change.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No Book found with the provided Book ID");
        }
    } catch (Exception e) {
        e.printStackTrace();
        
    }
    }//GEN-LAST:event_Button_SearchChange1ActionPerformed

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        DashBoard db = new DashBoard();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_exitActionPerformed

    private void Button_addbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_addbookMouseClicked
       boolean textFeilEmty = false;
        int bookid = Integer.parseInt(TextField_AddBookID.getText());
        String bookidtxt = TextField_AddBookID.getText();
        String bookName = TextField_BoookName.getText();
        String auother = TextField_Auother.getText();
        String date = TextField_Date1.getText();
        int quantity = Integer.parseInt(TextField_quantity.getText());
        String quantityText = TextField_quantity.getText();

        if (bookidtxt.equals("")) {
            Label_AddBookIDError.setVisible(true);
            Label_AddBookIDError.setText("Please Enetr the Book Id");
            textFeilEmty = false;
        }
        if (bookName.equals("")) {
            Label_BookNameError.setVisible(true);
            Label_BookNameError.setText("Please Enter The Book Name");
            textFeilEmty = false;
        }
        if (auother.equals("")) {
            Label_AuotherError.setVisible(true);
            Label_AuotherError.setText("Please Eneter The Auother Name");
            textFeilEmty = false;
        }
        if (date.equals("")) {
            Label_DateError.setVisible(true);
            Label_DateError.setText("Please Entere The Emill");
            textFeilEmty = false;
        }
        if (quantityText.equals("")) {
            Label_quantityError.setVisible(true);
            Label_quantityError.setText("Please  Enter The Quantity");
            textFeilEmty = false;
        }

        if (!textFeilEmty) {
            try {
                DBConnector dbc = new DBConnector();
                int status = dbc.AddBook(bookid, bookName, auother, date, quantity);
                if (status > 0) {
                    JOptionPane.showMessageDialog(null, "Book Add Success.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "PLease Try Again.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Button_addbookMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Remove;
    private javax.swing.JButton Button_SearchChange1;
    private javax.swing.JButton Button_addbook;
    private javax.swing.JButton Button_exit;
    private javax.swing.JLabel Label_AddBook;
    private javax.swing.JLabel Label_AddBookIDError;
    private javax.swing.JLabel Label_AddBookIDErrorChange1;
    private javax.swing.JLabel Label_AddressIcon4;
    private javax.swing.JLabel Label_AddressIcon5;
    private javax.swing.JLabel Label_Auother;
    private javax.swing.JLabel Label_AuotherError;
    private javax.swing.JLabel Label_BookAddDate;
    private javax.swing.JLabel Label_BookID;
    private javax.swing.JLabel Label_BookID1;
    private javax.swing.JLabel Label_BookIDChange1;
    private javax.swing.JLabel Label_BookName;
    private javax.swing.JLabel Label_BookNameError;
    private javax.swing.JLabel Label_ChangeDetails2;
    private javax.swing.JLabel Label_ContactNoIcon2;
    private javax.swing.JLabel Label_DateError;
    private javax.swing.JLabel Label_QuantityIcon;
    private javax.swing.JLabel Label_RemoveBook;
    private javax.swing.JLabel Label_RomoveBookIDError1;
    private javax.swing.JLabel Label_quantity;
    private javax.swing.JLabel Label_quantityError;
    private javax.swing.JLabel Label_studentNameIcon3;
    private javax.swing.JLabel Label_studentNameIcon4;
    private javax.swing.JLabel Label_studentNameIcon7;
    private javax.swing.JTextField TextField_AddBookID;
    private javax.swing.JTextField TextField_AddBookID3;
    private javax.swing.JTextField TextField_Auother;
    private javax.swing.JTextField TextField_BoookName;
    private javax.swing.JTextField TextField_Date1;
    private javax.swing.JTextField TextField_RemoveBook;
    private javax.swing.JTextField TextField_quantity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
