/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Kavisha Lashani
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    String emailRegex = "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$";
    
    public DashBoard() {
        initComponents();
        BookIssueTable();
        LabelBookReleaseErro.setVisible(false);
        try {
            DBConnector dbc = new DBConnector();
            int book = dbc.NOofBooks();
            Label_NoBooks3.setText("  " + book);            
            
            String name = dbc.GetName("pramod");                       
            if (name !=null && !name.isEmpty()) {
                Label_name.setText("WELCOME  " + name.toUpperCase());
            } else {
                Label_name.setText("WELCOME admin");
            }
            
            int student = dbc.NoofStudent();
            if (student > 0) {
                Label_NoStudents1.setText("  " + student);
            } else {
                Label_NoStudents1.setText("  0");
            }
            
            int issuedBook = dbc.NOofIssuedBook();
            if (issuedBook > 0) {
                Label_IssuedBooks.setText("  " + issuedBook);
            } else {
                Label_IssuedBooks.setText("  0");
            }
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Label_name = new javax.swing.JLabel();
        Label_notification = new javax.swing.JLabel();
        Label_bellIcon = new javax.swing.JLabel();
        Label_EditeAccount = new javax.swing.JLabel();
        Button_exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Button_BookIssue = new javax.swing.JButton();
        Button_BookDetails = new javax.swing.JButton();
        Button_StudentManagement = new javax.swing.JButton();
        Button_LogOut = new javax.swing.JButton();
        Button_AllStudentDetails = new javax.swing.JButton();
        Button_BookManage = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Home2 = new javax.swing.JPanel();
        Panel_NoBooks2 = new javax.swing.JPanel();
        Label_NoBooks3 = new javax.swing.JLabel();
        Panel_NoStudents = new javax.swing.JPanel();
        Label_NoStudents1 = new javax.swing.JLabel();
        Panel_IssuedBooks = new javax.swing.JPanel();
        Label_IssuedBooks = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueTable = new javax.swing.JTable();
        Label_DailyDetails = new javax.swing.JLabel();
        Label_Books = new javax.swing.JLabel();
        Label_Student = new javax.swing.JLabel();
        Label_issued = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Label_BookRelease = new javax.swing.JLabel();
        Label_BookIDRelease = new javax.swing.JLabel();
        LabelBookReleaseErro = new javax.swing.JLabel();
        Label_AddressIcon8 = new javax.swing.JLabel();
        Button_Release = new javax.swing.JButton();
        TextField_bookID = new javax.swing.JTextField();
        Label_AddressIcon9 = new javax.swing.JLabel();
        Label_BookIDRelease1 = new javax.swing.JLabel();
        TextField_studentID = new javax.swing.JTextField();
        LabelBookReleaseErro1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Panel_Top.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Digital Library");

        Label_name.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user (1).png"))); // NOI18N
        Label_name.setText("WELCOME");

        Label_bellIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bell.png"))); // NOI18N

        Label_EditeAccount.setText("Edit Account");

        Button_exit.setBackground(new java.awt.Color(153, 0, 0));
        Button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close (1).png"))); // NOI18N
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_TopLayout = new javax.swing.GroupLayout(Panel_Top);
        Panel_Top.setLayout(Panel_TopLayout);
        Panel_TopLayout.setHorizontalGroup(
            Panel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TopLayout.createSequentialGroup()
                .addContainerGap(467, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addGroup(Panel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TopLayout.createSequentialGroup()
                        .addComponent(Label_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TopLayout.createSequentialGroup()
                        .addComponent(Label_bellIcon)
                        .addGap(18, 18, 18)
                        .addComponent(Label_EditeAccount)
                        .addGap(18, 18, 18)))
                .addComponent(Label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_exit)
                .addContainerGap())
        );
        Panel_TopLayout.setVerticalGroup(
            Panel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TopLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_TopLayout.createSequentialGroup()
                        .addComponent(Button_exit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_TopLayout.createSequentialGroup()
                        .addGroup(Panel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TopLayout.createSequentialGroup()
                                .addComponent(Label_notification)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_bellIcon))
                            .addGroup(Panel_TopLayout.createSequentialGroup()
                                .addGroup(Panel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_EditeAccount))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        Button_BookIssue.setBackground(new java.awt.Color(169, 169, 169));
        Button_BookIssue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_BookIssue.setText("Book Issue");
        Button_BookIssue.setToolTipText("");
        Button_BookIssue.setBorder(null);
        Button_BookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BookIssueActionPerformed(evt);
            }
        });

        Button_BookDetails.setBackground(new java.awt.Color(169, 169, 169));
        Button_BookDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_BookDetails.setText("Book Details");
        Button_BookDetails.setBorder(null);
        Button_BookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BookDetailsActionPerformed(evt);
            }
        });

        Button_StudentManagement.setBackground(new java.awt.Color(169, 169, 169));
        Button_StudentManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_StudentManagement.setText("Student Manage");
        Button_StudentManagement.setBorder(null);
        Button_StudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_StudentManagementActionPerformed(evt);
            }
        });

        Button_LogOut.setBackground(new java.awt.Color(169, 169, 169));
        Button_LogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_LogOut.setText("LogOut");
        Button_LogOut.setBorder(null);
        Button_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LogOutActionPerformed(evt);
            }
        });

        Button_AllStudentDetails.setBackground(new java.awt.Color(169, 169, 169));
        Button_AllStudentDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_AllStudentDetails.setText("Student Details");
        Button_AllStudentDetails.setBorder(null);
        Button_AllStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AllStudentDetailsActionPerformed(evt);
            }
        });

        Button_BookManage.setBackground(new java.awt.Color(169, 169, 169));
        Button_BookManage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_BookManage.setText("Book Manage");
        Button_BookManage.setBorder(null);
        Button_BookManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BookManageActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(117, 16, 204));

        jLabel2.setBackground(new java.awt.Color(117, 16, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("                         Home");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_AllStudentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_BookIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_BookDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_StudentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(Button_BookManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Button_BookIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Button_AllStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Button_BookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Button_StudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Button_BookManage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        Panel_Home2.setBackground(new java.awt.Color(117, 16, 204));

        Panel_NoBooks2.setBackground(new java.awt.Color(51, 204, 0));

        Label_NoBooks3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Label_NoBooks3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/open-book.png"))); // NOI18N

        javax.swing.GroupLayout Panel_NoBooks2Layout = new javax.swing.GroupLayout(Panel_NoBooks2);
        Panel_NoBooks2.setLayout(Panel_NoBooks2Layout);
        Panel_NoBooks2Layout.setHorizontalGroup(
            Panel_NoBooks2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NoBooks2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Label_NoBooks3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        Panel_NoBooks2Layout.setVerticalGroup(
            Panel_NoBooks2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NoBooks2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Label_NoBooks3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Panel_NoStudents.setBackground(new java.awt.Color(0, 204, 0));
        Panel_NoStudents.setPreferredSize(new java.awt.Dimension(220, 100));

        Label_NoStudents1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Label_NoStudents1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reading-book.png"))); // NOI18N

        javax.swing.GroupLayout Panel_NoStudentsLayout = new javax.swing.GroupLayout(Panel_NoStudents);
        Panel_NoStudents.setLayout(Panel_NoStudentsLayout);
        Panel_NoStudentsLayout.setHorizontalGroup(
            Panel_NoStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NoStudentsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Label_NoStudents1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Panel_NoStudentsLayout.setVerticalGroup(
            Panel_NoStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NoStudentsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Label_NoStudents1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Panel_IssuedBooks.setBackground(new java.awt.Color(51, 204, 0));
        Panel_IssuedBooks.setPreferredSize(new java.awt.Dimension(220, 100));

        Label_IssuedBooks.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Label_IssuedBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/occupation.png"))); // NOI18N

        javax.swing.GroupLayout Panel_IssuedBooksLayout = new javax.swing.GroupLayout(Panel_IssuedBooks);
        Panel_IssuedBooks.setLayout(Panel_IssuedBooksLayout);
        Panel_IssuedBooksLayout.setHorizontalGroup(
            Panel_IssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_IssuedBooksLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(Label_IssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        Panel_IssuedBooksLayout.setVerticalGroup(
            Panel_IssuedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IssuedBooksLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Label_IssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        issueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Issued Date", "Returen Date", "Student ID"
            }
        ));
        jScrollPane1.setViewportView(issueTable);

        Label_DailyDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_DailyDetails.setText("Issued Books Details");

        Label_Books.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Books.setText("NO of Books");

        Label_Student.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Student.setText("NO of Students");

        Label_issued.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_issued.setText("NO of Issued Book");

        jPanel11.setBackground(new java.awt.Color(5, 11, 175));
        jPanel11.setPreferredSize(new java.awt.Dimension(420, 578));

        Label_BookRelease.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_BookRelease.setText("Release");

        Label_BookIDRelease.setText("Book ID");

        LabelBookReleaseErro.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        LabelBookReleaseErro.setForeground(new java.awt.Color(204, 0, 0));
        LabelBookReleaseErro.setText("Book Release");

        Label_AddressIcon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/open-book (1).png"))); // NOI18N

        Button_Release.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_Release.setText("Release");
        Button_Release.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ReleaseActionPerformed(evt);
            }
        });

        TextField_bookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_bookIDKeyPressed(evt);
            }
        });

        Label_AddressIcon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N

        Label_BookIDRelease1.setText("Student ID");

        TextField_studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_studentIDKeyPressed(evt);
            }
        });

        LabelBookReleaseErro1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        LabelBookReleaseErro1.setForeground(new java.awt.Color(204, 0, 0));
        LabelBookReleaseErro1.setText("Book Release");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Button_Release, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Label_BookRelease, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(Label_AddressIcon8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelBookReleaseErro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_bookID, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(Label_AddressIcon9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelBookReleaseErro1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_BookIDRelease, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_BookIDRelease1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Label_BookRelease)
                .addGap(18, 18, 18)
                .addComponent(Label_BookIDRelease)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Label_AddressIcon8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_bookID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelBookReleaseErro)))
                .addGap(18, 18, 18)
                .addComponent(Label_BookIDRelease1)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Label_AddressIcon9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelBookReleaseErro1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Release, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout Panel_Home2Layout = new javax.swing.GroupLayout(Panel_Home2);
        Panel_Home2.setLayout(Panel_Home2Layout);
        Panel_Home2Layout.setHorizontalGroup(
            Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Home2Layout.createSequentialGroup()
                .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Panel_Home2Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(Label_Books)
                            .addGap(275, 275, 275)
                            .addComponent(Label_Student))
                        .addGroup(Panel_Home2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Panel_Home2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Panel_Home2Layout.createSequentialGroup()
                                    .addGap(176, 176, 176)
                                    .addComponent(Label_DailyDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Panel_Home2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Panel_NoBooks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(Panel_NoStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_issued)
                            .addComponent(Panel_IssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Home2Layout.setVerticalGroup(
            Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Home2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Books)
                    .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_Student)
                        .addComponent(Label_issued)))
                .addGap(18, 18, 18)
                .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_NoBooks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_NoStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_IssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(Panel_Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Home2Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Home2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label_DailyDetails)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Home2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Home2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BookIssueActionPerformed
        BookIssue bookIssue = new BookIssue();
        bookIssue.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_BookIssueActionPerformed

    private void Button_AllStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AllStudentDetailsActionPerformed
        StudentsDetails studentsDetails = new StudentsDetails();
        studentsDetails.setVisible(true);
    }//GEN-LAST:event_Button_AllStudentDetailsActionPerformed

    private void Button_BookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BookDetailsActionPerformed
        BookDetails bookDetails = new BookDetails();
        bookDetails.setVisible(true);
    }//GEN-LAST:event_Button_BookDetailsActionPerformed

    private void Button_StudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_StudentManagementActionPerformed
       Studentmanagement studentmanagement = new Studentmanagement();
        studentmanagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_StudentManagementActionPerformed
  
    public void BookIssueTable() {
        try {
            DBConnector dbc = new DBConnector();

            Object[][] data = dbc.BookIssueTable();
            int rows = data.length;

            DefaultTableModel tableModel = (DefaultTableModel) issueTable.getModel();
            for (Object[] row : data) {
                tableModel.addRow(row);
            }
            DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
            leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);

            for (int i = 0; i < issueTable.getColumnCount(); i++) {
                issueTable.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
            }
            issueTable.setDefaultEditor(Object.class, null);

        } catch (SQLException ex) {
            Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void Button_BookManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BookManageActionPerformed
        BookManagement bookManagement = new BookManagement();
        bookManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_BookManageActionPerformed

    private void Button_ReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ReleaseActionPerformed
        String bookIdtxt = TextField_bookID.getText();
        int bookId = Integer.parseInt(TextField_bookID.getText());
        int studentID = Integer.parseInt(TextField_studentID.getText());
        
        if (bookIdtxt.equals("")) {
            LabelBookReleaseErro.setVisible(true);
            LabelBookReleaseErro.setText("Please Enter book Id.");
        } else {
            try {
                
                DBConnector dbc = new DBConnector();
                int status = dbc.BookRelease(bookId,studentID);
                if (status > 0) {
                    JOptionPane.showMessageDialog(null, "Success.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "PLease try again", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_Button_ReleaseActionPerformed

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        dispose();
    }//GEN-LAST:event_Button_exitActionPerformed

    private void TextField_bookIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_bookIDKeyPressed
       LabelBookReleaseErro.setVisible(false);
    }//GEN-LAST:event_TextField_bookIDKeyPressed

    private void TextField_studentIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_studentIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_studentIDKeyPressed

    private void Button_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LogOutActionPerformed
        Login_Page lp = new Login_Page();
        lp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Button_LogOutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_AllStudentDetails;
    private javax.swing.JButton Button_BookDetails;
    private javax.swing.JButton Button_BookIssue;
    private javax.swing.JButton Button_BookManage;
    private javax.swing.JButton Button_LogOut;
    private javax.swing.JButton Button_Release;
    private javax.swing.JButton Button_StudentManagement;
    private javax.swing.JButton Button_exit;
    private javax.swing.JLabel LabelBookReleaseErro;
    private javax.swing.JLabel LabelBookReleaseErro1;
    private javax.swing.JLabel Label_AddressIcon8;
    private javax.swing.JLabel Label_AddressIcon9;
    private javax.swing.JLabel Label_BookIDRelease;
    private javax.swing.JLabel Label_BookIDRelease1;
    private javax.swing.JLabel Label_BookRelease;
    private javax.swing.JLabel Label_Books;
    private javax.swing.JLabel Label_DailyDetails;
    private javax.swing.JLabel Label_EditeAccount;
    private javax.swing.JLabel Label_IssuedBooks;
    private javax.swing.JLabel Label_NoBooks3;
    private javax.swing.JLabel Label_NoStudents1;
    private javax.swing.JLabel Label_Student;
    private javax.swing.JLabel Label_bellIcon;
    private javax.swing.JLabel Label_issued;
    private javax.swing.JLabel Label_name;
    private javax.swing.JLabel Label_notification;
    private javax.swing.JPanel Panel_Home2;
    private javax.swing.JPanel Panel_IssuedBooks;
    private javax.swing.JPanel Panel_NoBooks2;
    private javax.swing.JPanel Panel_NoStudents;
    private javax.swing.JPanel Panel_Top;
    private javax.swing.JTextField TextField_bookID;
    private javax.swing.JTextField TextField_studentID;
    private javax.swing.JTable issueTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
