/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.security.interfaces.DSAKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavisha Lashani
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
        Label_UserNameError.setVisible(false);
        Label_PasswordError.setVisible(false);
        Label_LoginError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Login = new javax.swing.JLabel();
        Label_Login1 = new javax.swing.JLabel();
        TextField_Password = new javax.swing.JTextField();
        Label_EmailLogin = new javax.swing.JLabel();
        Label_UserNameError = new javax.swing.JLabel();
        Label_Password = new javax.swing.JLabel();
        TextField_EmailLogin = new javax.swing.JTextField();
        Label_PIcon = new javax.swing.JLabel();
        Label_UIcon = new javax.swing.JLabel();
        Label_PasswordError = new javax.swing.JLabel();
        Button_SignUp = new javax.swing.JButton();
        Button_Login = new javax.swing.JButton();
        Label_ContactNumber2 = new javax.swing.JLabel();
        Label_CreateAnAccount = new javax.swing.JLabel();
        Label_LoginError = new javax.swing.JLabel();
        Button_exit = new javax.swing.JButton();
        Label_BImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 19, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 720));

        Label_Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Login.setText(" Login Yor Account");
        Label_Login.setToolTipText("");

        Label_Login1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Login1.setText("Login");
        Label_Login1.setToolTipText("");

        TextField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_PasswordKeyPressed(evt);
            }
        });

        Label_EmailLogin.setText("Email");
        Label_EmailLogin.setToolTipText("");

        Label_UserNameError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_UserNameError.setForeground(new java.awt.Color(255, 0, 0));
        Label_UserNameError.setText("User Name");
        Label_UserNameError.setToolTipText("");

        Label_Password.setText("Password");
        Label_Password.setToolTipText("");

        TextField_EmailLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_EmailLoginKeyPressed(evt);
            }
        });

        Label_PIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/padlock.png"))); // NOI18N
        Label_PIcon.setToolTipText("");

        Label_UIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user (1).png"))); // NOI18N
        Label_UIcon.setToolTipText("");

        Label_PasswordError.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_PasswordError.setForeground(new java.awt.Color(255, 0, 0));
        Label_PasswordError.setText("Password");
        Label_PasswordError.setToolTipText("");

        Button_SignUp.setBackground(new java.awt.Color(11, 168, 145));
        Button_SignUp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Button_SignUp.setText("SignUp");
        Button_SignUp.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 1));
        Button_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SignUpActionPerformed(evt);
            }
        });

        Button_Login.setBackground(new java.awt.Color(11, 168, 145));
        Button_Login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Button_Login.setText("Login");
        Button_Login.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 1));
        Button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoginActionPerformed(evt);
            }
        });

        Label_ContactNumber2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_ContactNumber2.setForeground(new java.awt.Color(255, 255, 255));
        Label_ContactNumber2.setText("or");

        Label_CreateAnAccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_CreateAnAccount.setForeground(new java.awt.Color(255, 255, 255));
        Label_CreateAnAccount.setText("Create An Account");

        Label_LoginError.setForeground(new java.awt.Color(255, 0, 0));
        Label_LoginError.setText("Login Error");
        Label_LoginError.setToolTipText("");

        Button_exit.setBackground(new java.awt.Color(153, 0, 0));
        Button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close (1).png"))); // NOI18N
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_PIcon)
                            .addComponent(Label_UIcon))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_PasswordError)
                            .addComponent(Label_Password)
                            .addComponent(Label_UserNameError)
                            .addComponent(Label_EmailLogin)
                            .addComponent(TextField_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(TextField_EmailLogin)
                            .addComponent(Label_LoginError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_CreateAnAccount)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Label_Login1)
                                    .addGap(151, 151, 151))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Label_Login)
                                    .addGap(124, 124, 124))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Label_ContactNumber2)
                                    .addGap(191, 191, 191))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(132, 132, 132)))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_exit)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Login1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_Login)
                        .addGap(76, 76, 76)
                        .addComponent(Label_EmailLogin)
                        .addGap(18, 18, 18)
                        .addComponent(TextField_EmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_UIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_UserNameError)
                .addGap(32, 32, 32)
                .addComponent(Label_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_PIcon)
                    .addComponent(TextField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_PasswordError)
                .addGap(32, 32, 32)
                .addComponent(Label_LoginError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_ContactNumber2)
                .addGap(18, 18, 18)
                .addComponent(Label_CreateAnAccount)
                .addGap(18, 18, 18)
                .addComponent(Button_SignUp)
                .addGap(106, 106, 106))
        );

        Label_BImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/books-5211309_12801.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Label_BImage, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_BImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoginActionPerformed

        String email = TextField_EmailLogin.getText();
        String password = TextField_Password.getText();
        boolean feildEmty = false;
        String emailRegex = "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$";

        if (email.equals("") || !email.matches(emailRegex)) {
            Label_UserNameError.setVisible(true);
            Label_UserNameError.setText("Please Enter valid Email");
            feildEmty = true;
        }
        if (password.equals("")) {
            Label_PasswordError.setVisible(true);
            Label_PasswordError.setText("Please Enter The Password");
            feildEmty = true;
        }
        if (!feildEmty) {

            try {
                DBConnector dbc = new DBConnector();
                boolean status = dbc.Loging(email, password);

                if (status) {
                    DashBoard dashBoard = new DashBoard();
                    dashBoard.setVisible(true);
                    this.dispose();
                } else {
                    Label_LoginError.setVisible(true);
                    Label_LoginError.setText("Please Check The Email And Password");
                }

            } catch (Exception ex) {
                Logger.getLogger(SignUp_Page.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Button_LoginActionPerformed

    private void Button_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SignUpActionPerformed
        SignUp_Page signUp_Page = new SignUp_Page();
        signUp_Page.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Button_SignUpActionPerformed

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        dispose();
    }//GEN-LAST:event_Button_exitActionPerformed

    private void TextField_EmailLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_EmailLoginKeyPressed
        Label_UserNameError.setVisible(false);
        Label_LoginError.setVisible(false);
    }//GEN-LAST:event_TextField_EmailLoginKeyPressed

    private void TextField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_PasswordKeyPressed
        Label_PasswordError.setVisible(false);
        Label_LoginError.setVisible(false);
    }//GEN-LAST:event_TextField_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Login;
    private javax.swing.JButton Button_SignUp;
    private javax.swing.JButton Button_exit;
    private javax.swing.JLabel Label_BImage;
    private javax.swing.JLabel Label_ContactNumber2;
    private javax.swing.JLabel Label_CreateAnAccount;
    private javax.swing.JLabel Label_EmailLogin;
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Login1;
    private javax.swing.JLabel Label_LoginError;
    private javax.swing.JLabel Label_PIcon;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_PasswordError;
    private javax.swing.JLabel Label_UIcon;
    private javax.swing.JLabel Label_UserNameError;
    private javax.swing.JTextField TextField_EmailLogin;
    private javax.swing.JTextField TextField_Password;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
