/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavisha Lashani
 */
public class Studentmanagement extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public Studentmanagement() {
        initComponents();
        Label_studentNameError1.setVisible(false);
        Label_AddressError1.setVisible(false);
        Label_EmailEError2.setVisible(false);
        Label_ContactNoError1.setVisible(false);
        Label_EmailEError3.setVisible(false);
        Label_EmailEErrorChangeDetails2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_AddStudent1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Label_AddStudent1 = new javax.swing.JLabel();
        Label_studentName1 = new javax.swing.JLabel();
        Label_studentNameError1 = new javax.swing.JLabel();
        Label_Address2 = new javax.swing.JLabel();
        TextField_Email3 = new javax.swing.JTextField();
        Label_AddressError1 = new javax.swing.JLabel();
        Label_Email2 = new javax.swing.JLabel();
        Label_EmailEError2 = new javax.swing.JLabel();
        Label_ContactNo1 = new javax.swing.JLabel();
        Label_AddressIcon4 = new javax.swing.JLabel();
        Button_addStudent1 = new javax.swing.JButton();
        TextField_Studentname = new javax.swing.JTextField();
        Label_studentNameIcon3 = new javax.swing.JLabel();
        TextField_Address4 = new javax.swing.JTextField();
        Label_AddressIcon5 = new javax.swing.JLabel();
        TextField_ContactNo2 = new javax.swing.JTextField();
        Label_ContactNoIcon2 = new javax.swing.JLabel();
        Label_ContactNoError1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Label_RemoveStudent1 = new javax.swing.JLabel();
        Label_studentID = new javax.swing.JLabel();
        Label_EmailEError3 = new javax.swing.JLabel();
        Label_AddressIcon6 = new javax.swing.JLabel();
        Button_Delete1 = new javax.swing.JButton();
        TextField_StudentID = new javax.swing.JTextField();
        Button_deletestudent = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        Label_EditeStudentDetails4 = new javax.swing.JLabel();
        TextField_stID = new javax.swing.JTextField();
        Label_stID = new javax.swing.JLabel();
        Label_AddressIconChangeDetails2 = new javax.swing.JLabel();
        Label_EmailEErrorChangeDetails2 = new javax.swing.JLabel();
        Button_Search2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Button_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_AddStudent1.setBackground(new java.awt.Color(117, 16, 204));

        jPanel7.setBackground(new java.awt.Color(5, 11, 175));
        jPanel7.setPreferredSize(new java.awt.Dimension(420, 578));

        Label_AddStudent1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_AddStudent1.setText("Add Student");

        Label_studentName1.setText("Student Name");

        Label_studentNameError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_studentNameError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_studentNameError1.setText("Student Name");

        Label_Address2.setText("Address");

        Label_AddressError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_AddressError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_AddressError1.setText("Address");

        Label_Email2.setText("Email");

        Label_EmailEError2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_EmailEError2.setForeground(new java.awt.Color(204, 0, 0));
        Label_EmailEError2.setText("Email");

        Label_ContactNo1.setText("Contact Number");

        Label_AddressIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email.png"))); // NOI18N

        Button_addStudent1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_addStudent1.setText("ADD");
        Button_addStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_addStudent1ActionPerformed(evt);
            }
        });

        TextField_Studentname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_StudentnameKeyPressed(evt);
            }
        });

        Label_studentNameIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N

        TextField_Address4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_Address4KeyPressed(evt);
            }
        });

        Label_AddressIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/address.png"))); // NOI18N

        Label_ContactNoIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-contact.png"))); // NOI18N

        Label_ContactNoError1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_ContactNoError1.setForeground(new java.awt.Color(204, 0, 0));
        Label_ContactNoError1.setText("Contact Number");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_AddressIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_ContactNoError1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Label_EmailEError2)
                        .addComponent(Label_Email2)
                        .addComponent(Label_studentName1)
                        .addComponent(Label_ContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(Label_studentNameError1))
                        .addComponent(Label_AddressError1)
                        .addComponent(Label_Address2)
                        .addComponent(TextField_Address4, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(TextField_Email3)))
                .addGap(434, 434, 434))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Label_AddStudent1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Button_addStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(TextField_Studentname)
                    .addGap(433, 433, 433)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Label_studentNameIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(706, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Label_AddressIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(706, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(TextField_ContactNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(424, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Label_ContactNoIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(706, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_AddStudent1)
                .addGap(18, 18, 18)
                .addComponent(Label_studentName1)
                .addGap(56, 56, 56)
                .addComponent(Label_studentNameError1)
                .addGap(18, 18, 18)
                .addComponent(Label_Address2)
                .addGap(18, 18, 18)
                .addComponent(TextField_Address4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_AddressError1)
                .addGap(27, 27, 27)
                .addComponent(Label_Email2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_AddressIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Email3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_EmailEError2)
                .addGap(64, 64, 64)
                .addComponent(Label_ContactNo1)
                .addGap(18, 18, 18)
                .addComponent(Label_ContactNoError1)
                .addGap(51, 51, 51)
                .addComponent(Button_addStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(TextField_Studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(457, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(Label_studentNameIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(Label_AddressIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(344, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(372, Short.MAX_VALUE)
                    .addComponent(TextField_ContactNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(176, 176, 176)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(372, Short.MAX_VALUE)
                    .addComponent(Label_ContactNoIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(176, 176, 176)))
        );

        jPanel8.setBackground(new java.awt.Color(5, 11, 175));
        jPanel8.setPreferredSize(new java.awt.Dimension(420, 578));

        Label_RemoveStudent1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_RemoveStudent1.setText("Delete Student");

        Label_studentID.setText("Student ID");

        Label_EmailEError3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_EmailEError3.setForeground(new java.awt.Color(204, 0, 0));
        Label_EmailEError3.setText("Email");

        Label_AddressIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/id.png"))); // NOI18N

        Button_Delete1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_Delete1.setText("Remove");

        Button_deletestudent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_deletestudent.setText("Delete");
        Button_deletestudent.setActionCommand("Delete");
        Button_deletestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_deletestudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Label_RemoveStudent1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_EmailEError3)
                                    .addComponent(Label_studentID)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(Button_deletestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(240, 240, 240)
                        .addComponent(Button_Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_AddressIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_RemoveStudent1)
                .addGap(47, 47, 47)
                .addComponent(Label_studentID)
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_AddressIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(Label_EmailEError3)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Button_Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_deletestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );

        Button_deletestudent.getAccessibleContext().setAccessibleName("Delete");

        jPanel11.setBackground(new java.awt.Color(5, 11, 175));

        Label_EditeStudentDetails4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_EditeStudentDetails4.setText("Change Student Details");

        Label_stID.setText("Enter Student ID");

        Label_AddressIconChangeDetails2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/id.png"))); // NOI18N

        Label_EmailEErrorChangeDetails2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Label_EmailEErrorChangeDetails2.setForeground(new java.awt.Color(204, 0, 0));
        Label_EmailEErrorChangeDetails2.setText("Email");

        Button_Search2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_Search2.setText("Search");
        Button_Search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Search2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Label_AddressIconChangeDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_stID)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addComponent(Label_EditeStudentDetails4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                            .addComponent(TextField_stID, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)))
                    .addComponent(Label_EmailEErrorChangeDetails2)))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(Button_Search2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Label_EditeStudentDetails4)
                .addGap(18, 18, 18)
                .addComponent(Label_stID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_stID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_AddressIconChangeDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_EmailEErrorChangeDetails2)
                .addGap(18, 18, 18)
                .addComponent(Button_Search2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Label_stID.getAccessibleContext().setAccessibleName("Enter Student ID");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Button_exit.setBackground(new java.awt.Color(153, 0, 0));
        Button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close (1).png"))); // NOI18N
        Button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_exit)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_exit)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_AddStudent1Layout = new javax.swing.GroupLayout(Panel_AddStudent1);
        Panel_AddStudent1.setLayout(Panel_AddStudent1Layout);
        Panel_AddStudent1Layout.setHorizontalGroup(
            Panel_AddStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AddStudent1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_AddStudent1Layout.setVerticalGroup(
            Panel_AddStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AddStudent1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(Panel_AddStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AddStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_AddStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_exitActionPerformed
        dispose();
        DashBoard db = new DashBoard();
        db.setVisible(true);
    }//GEN-LAST:event_Button_exitActionPerformed

    private void Button_addStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_addStudent1ActionPerformed
        String studentName = TextField_Studentname.getText();
        String address = TextField_Address4.getText();
        String email = TextField_Email3.getText();
        String contact = TextField_ContactNo2.getText();

        if (studentName.equals("")) {

        }
        if (address.equals("")) {

        }
        if (email.equals("")) {

        }
        if (contact.equals("")) {

        }
        
        try {
        DBConnector dbConnector = new DBConnector();
        int result = dbConnector.AddStudent(studentName, address, email, contact);
        
        if (result > 0) {
            DBConnector dbC = new DBConnector();
            int StID = dbC.lastStudenID ();
            JOptionPane.showMessageDialog(null, "Student added successfully!\nYour Student ID is : "+StID);
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add student.");
        }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_Button_addStudent1ActionPerformed

    private void Button_deletestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_deletestudentActionPerformed
        int stID = Integer.parseInt(TextField_StudentID.getText());

        try {
        DBConnector dbConnector = new DBConnector();
        int result = dbConnector.DeleteStudentByID(stID);
        
        if (result > 0) {
            JOptionPane.showMessageDialog(null, "Student deleted successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "No student found with the provided Student ID.");
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Button_deletestudentActionPerformed

    private void Button_Search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Search2ActionPerformed
        int stID = Integer.parseInt(TextField_stID.getText());


    try {
        DBConnector dbConnector = new DBConnector();
        boolean exists = dbConnector.CheckStudentID(stID);
        
        if (exists) {
            changeStudentDetails change = new changeStudentDetails(stID);
            change.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No student found with the provided Student ID");
        }
    } catch (Exception e) {
        e.printStackTrace();
        
    }
    }//GEN-LAST:event_Button_Search2ActionPerformed

    private void TextField_StudentnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_StudentnameKeyPressed
        Label_studentNameError1.setVisible(false);
    }//GEN-LAST:event_TextField_StudentnameKeyPressed

    private void TextField_Address4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_Address4KeyPressed
        Label_AddressError1.setVisible(false);
    }//GEN-LAST:event_TextField_Address4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentmanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Delete1;
    private javax.swing.JButton Button_Search2;
    private javax.swing.JButton Button_addStudent1;
    private javax.swing.JButton Button_deletestudent;
    private javax.swing.JButton Button_exit;
    private javax.swing.JLabel Label_AddStudent1;
    private javax.swing.JLabel Label_Address2;
    private javax.swing.JLabel Label_AddressError1;
    private javax.swing.JLabel Label_AddressIcon4;
    private javax.swing.JLabel Label_AddressIcon5;
    private javax.swing.JLabel Label_AddressIcon6;
    private javax.swing.JLabel Label_AddressIconChangeDetails2;
    private javax.swing.JLabel Label_ContactNo1;
    private javax.swing.JLabel Label_ContactNoError1;
    private javax.swing.JLabel Label_ContactNoIcon2;
    private javax.swing.JLabel Label_EditeStudentDetails4;
    private javax.swing.JLabel Label_Email2;
    private javax.swing.JLabel Label_EmailEError2;
    private javax.swing.JLabel Label_EmailEError3;
    private javax.swing.JLabel Label_EmailEErrorChangeDetails2;
    private javax.swing.JLabel Label_RemoveStudent1;
    private javax.swing.JLabel Label_stID;
    private javax.swing.JLabel Label_studentID;
    private javax.swing.JLabel Label_studentName1;
    private javax.swing.JLabel Label_studentNameError1;
    private javax.swing.JLabel Label_studentNameIcon3;
    private javax.swing.JPanel Panel_AddStudent1;
    private javax.swing.JTextField TextField_Address4;
    private javax.swing.JTextField TextField_ContactNo2;
    private javax.swing.JTextField TextField_Email3;
    private javax.swing.JTextField TextField_StudentID;
    private javax.swing.JTextField TextField_Studentname;
    private javax.swing.JTextField TextField_stID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
